## Joining Arrays
Numpy uses the concept of stacking, providing a number of functions in this regard.
vstack() function, which combines the second array as new rows of the first array. In this case, the array grows in a vertical direction.
hstack() function performs horizontal stacking; that is, the second array is added to the columns of the first array.

In [1]:
import numpy as np

In [4]:
A = np.ones((3,3))
B = np.zeros((3,3))

In [6]:
np.vstack((A,B))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.hstack((A,B))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

Other functions performing stacking between multiple arrays are column_stack() and row_stack(). These functions operate differently than the two previous functions.<br>Generally these functions are used with one-dimensional arrays, which are stacked as columns or rows in order to form a new 2-D array.</br>

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

In [9]:
np.column_stack((a,b,c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
np.row_stack((a,b,c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Splitting Arrays
<p>Using functions like vsplit() and hsplit()

In [12]:
A = np.arange(0,16).reshape(4,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
# Splitting horizontally(Column-wise). hsplit() is equivalent to split with axis = 1. The array is always split along 
# the second axis regardless the array dimension.
## Splitting will result in equal parts only. If the splitting isn't in equal parts, the program will throw an error.
[B,C] = np.hsplit(A,2)

In [20]:
B

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [21]:
C

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [22]:
# Splitting vertically(Row-wise). Using vsplit()
[B,C] = np.vsplit(A,2)

In [23]:
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
C

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
# Splitting arrays in unequal parts. Using the split(arr, index of column or row as a list, axis).
# Horizontal splitting
[A1,A2,A3] = np.split(A,[2,3],axis=1)

In [27]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [28]:
A2

array([[ 2],
       [ 6],
       [10],
       [14]])

In [29]:
A3

array([[ 3],
       [ 7],
       [11],
       [15]])

In [36]:
# Vertical splitting
[A1,A2,A3] = np.split(A,[1,2],axis=0)

In [37]:
A1

array([[0, 1, 2, 3]])

In [38]:
A2

array([[4, 5, 6, 7]])

In [39]:
A3

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])