## Numpy Basics

In [1]:
import numpy as np

In [39]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [3]:
#Checks the object type
type(arr)

numpy.ndarray

In [4]:
#Checks the associated datatype
arr.dtype

dtype('int64')

In [5]:
#n-dimensional array dimension or axis
arr.ndim

1

In [6]:
#Size of the array or number of elements/ array length
arr.size

3

In [40]:
#Shape of the array as a matrix 
arr.shape

(3,)

In [8]:
#Two dimensional array
arr2 = np.array([[1.3,2.6,3.4],[4.1,5.4,6.9]])
arr2

array([[1.3, 2.6, 3.4],
       [4.1, 5.4, 6.9]])

In [9]:
arr2.dtype

dtype('float64')

In [10]:
arr2.ndim

2

In [11]:
arr2.shape

(2, 3)

In [12]:
b = np.array([(1,2,3),[4,5,6],(7,8,9)])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
b.ndim

2

In [14]:
b.shape

(3, 3)

In [15]:
b.size

9

In [16]:
#itemsize deines the size in bytes of each item in the array
b.itemsize

8

In [17]:
b.data

In [18]:
#Can also accept tuples and sequence of tuples
c = np.array((1,2,3))
c

array([1, 2, 3])

In [19]:
d = np.array(((1,2,3),(4,5,6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
#Using the data type string
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [21]:
g.dtype

dtype('<U1')

In [22]:
g.dtype.name

'str32'

In [23]:
#Specifying the data type explicitly 
f = np.array([[1,2,3],[4,5,6]],dtype=complex)
f

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]])

## Intrinsic creation of an array
Enables us to generate arrays with initial content, created with different values depending on the function 

In [41]:
#Zeros function 
np.zeros((2,3),dtype="int32")

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [25]:
#Ones function 
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [26]:
#These functions create arrays with the default data type = float64

In [27]:
#np.arange(start,end[not including],step_size)

In [28]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(9,20)

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [30]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

In [31]:
np.arange(0,6,0.6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. , 3.6, 4.2, 4.8, 5.4])

In [32]:
#reshape() function divides a linear array in different parts in the manner specified by the shape argument 

In [33]:
np.arange(0,12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [34]:
#linspace() is similar to arange but the third argument, instead of specifying the distance between two elements,
#defines the number of elements into which we want the interval to be split\
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [50]:
#random() function of the numpy.random module.
#Will generate as many random elements as specified in the function argument
np.random.random(10)

array([0.91157034, 0.76654551, 0.85425026, 0.72602398, 0.45133454,
       0.7070818 , 0.31353674, 0.09544653, 0.74360603, 0.89102591])

In [36]:
np.random.random((2,4))

array([[0.13158607, 0.02797867, 0.15197299, 0.56759554],
       [0.26698719, 0.26180182, 0.9719548 , 0.30536343]])