In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])

In [4]:
# Array 'b' is just another way of calling array 'a'. No new array is created.
b=a
b

array([1, 2, 3, 4])

In [5]:
a[2]=0
b

array([1, 2, 0, 4])

In [6]:
# When you slice an array, the object returned is a view of the original array 
c = a[0:2]
c

array([1, 2])

In [7]:
# Even when slicing, you are actually pointing to the same object.
a[0] = 0
c

array([0, 2])

In [8]:
# To create a completely new and distinct array, use the copy() function.
a = np.array([1,2,3,4])
c = a.copy()
c

array([1, 2, 3, 4])

In [9]:
# Array 'c' remains unchanged
a[0] = 0
c

array([1, 2, 3, 4])

## Vectorization
It is the absence of an explicit loop during the developing of the code. They are not actually omitted but are implemented internally and then replaced by other constructs in the code.<br>For example, <li>multiplication of two arrays : a * b or,</li><li>multiplication of two matrices : a * b</li></br>

## Broadcasting
It allows an operator or a function to act on two or more arrays to operate even if these arrays do not have the same shape. Not all dimensions can be subjected to broadcasting; they must meet certain rules.<br>Two arrays can be subjected to broadcasting when all their dimensions are compatible, i.e., the length of each dimension must be equal or one of them must be equal to 1. If neither of these conditions is met, you get an exception that states that the
two arrays are not compatible.</br>

In [32]:
A = np.arange(16).reshape(4,4)
b = np.arange(4)

In [33]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
b

array([0, 1, 2, 3])

In [35]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

In [39]:
m = np.arange(6).reshape(3,1,2)
n = np.arange(6).reshape(3,2,1)

In [40]:
m

array([[[0, 1]],

       [[2, 3]],

       [[4, 5]]])

In [16]:
n

array([[[0],
        [1]],

       [[2],
        [3]],

       [[4],
        [5]]])

In [17]:
m+n

array([[[ 0,  1],
        [ 1,  2]],

       [[ 4,  5],
        [ 5,  6]],

       [[ 8,  9],
        [ 9, 10]]])

## Structured Arrays
Numpy allows you to create arrays that are much more complex than 1-D/2-D arrays not only in size, but in the structured, called structured arrays.

In [18]:
structured = np.array([(1, "First", 0.5, 1+2j),(2, 'Second', 1.3, 2-2j),(3, 'Third', 0.8, 1+3j)],dtype=('i2,a6,f4,c8'))

In [19]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [20]:
structured = np.array([(1, 'First', 0.5, 1+2j),(2, 'Second', 1.3,2-2j),(3, 'Third', 0.8, 1+3j)],dtype=('int16, a6, float32, complex64'))

In [21]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('f0', '<i2'), ('f1', 'S6'), ('f2', '<f4'), ('f3', '<c8')])

In [22]:
structured[1]

(2, b'Second', 1.3, 2.-2.j)

In [23]:
structured['f1']

array([b'First', b'Second', b'Third'], dtype='|S6')

In [24]:
# Specifying names which are more meaningful
structured = np.array([(1,'First',0.5,1+2j),(2,'Second',1.3,2-2j),(3,'Third',0.8,1+3j)],dtype=[('id','i2'),('position','a6'),('value','f4'),('complex','c8')])

In [25]:
structured

array([(1, b'First', 0.5, 1.+2.j), (2, b'Second', 1.3, 2.-2.j),
       (3, b'Third', 0.8, 1.+3.j)],
      dtype=[('id', '<i2'), ('position', 'S6'), ('value', '<f4'), ('complex', '<c8')])

In [26]:
# Can even be done later
structured.dtype.names = ('id','order','value','complex')

In [27]:
# Now we can use meaningful names for the various field types
structured['complex']

array([1.+2.j, 2.-2.j, 1.+3.j], dtype=complex64)