In [1]:
import numpy as np
import pandas as pd

In [3]:
a = np.arange(8).reshape(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [19]:
import numpy as np
x = np.random.random(4)
y = np.random.random(4)
cov_mat = np.stack((x, y), axis = 1)
print(np.cov(cov_mat))

[[ 0.00305956  0.01926081 -0.00806028 -0.02095868]
 [ 0.01926081  0.1212525  -0.05074185 -0.13194107]
 [-0.00806028 -0.05074185  0.02123449  0.05521481]
 [-0.02095868 -0.13194107  0.05521481  0.14357186]]
