In [2]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
a.ndim

1

In [7]:
a.shape

(3,)

In [8]:
type(a)

numpy.ndarray

In [9]:
a.dtype

dtype('int32')

In [10]:
b = np.array([[1,2,3],[4,5,6]])

In [11]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
type(b)

numpy.ndarray

In [13]:
e = np.array([(1,2,3), [4,5,6], (7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b.shape

(2, 3)

In [15]:
b.ndim

2

In [16]:
b.dtype

dtype('int32')

In [17]:
b.size

6

In [18]:
b[0]

array([1, 2, 3])

In [19]:
b[0,1]

2

In [20]:
b[0,0]

1

In [21]:
a[0]

1

In [22]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
d = np.array([(1,2,3), [4,5,6], (7,8,9)], dtype = complex)
d

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j],
       [7.+0.j, 8.+0.j, 9.+0.j]])

In [25]:
f = np.arange(4)
f

array([0, 1, 2, 3])

In [26]:
g = np.arange(4,8)
g

array([4, 5, 6, 7])

In [27]:
f + g

array([ 4,  6,  8, 10])

In [28]:
f- g

array([-4, -4, -4, -4])

In [29]:
f*g

array([ 0,  5, 12, 21])

In [30]:
# write a program to perform summation on the array using numpy:
m1 = np.arange(1,16).reshape(3,5)
m1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
m1.shape

(3, 5)

In [32]:
m1.ndim

2

In [33]:
m1.sum(axis=0) #sum of elements in columns

array([18, 21, 24, 27, 30])

In [34]:
m1.sum(axis=1) #sum of elements in rows

array([15, 40, 65])

In [35]:
# write a python program for matrix multiplication using numpy functions [np.dot, np.matmul, variable1@variable2]
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.dot(v1,v2)

32

In [36]:
np.matmul(v1,v2)

32

In [37]:
v1@v2

32

In [38]:
# multiplication of 3 x 3 matrix
s1 = np.arange(1,10).reshape(3,3)
s1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
s2 = np.arange(9,0,-1).reshape(3,3)
s2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [40]:
np.dot(s1,s2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [41]:
np.matmul(s1,s2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [42]:
s1@s2

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [5]:
--allow-chromium-download

NameError: name 'allow' is not defined